//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingVS.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class tblProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProduct()
        {
            this.tblCarts = new HashSet<tblCart>();
            this.tblOrders = new HashSet<tblOrder>();
        }
        [DataMember]
        public int productid { get; set; }
        [DataMember]
        public string productname { get; set; }
        [DataMember]
        public Nullable<double> productprice { get; set; }
        [DataMember]
        public Nullable<int> productquantity { get; set; }
        [DataMember]
        public string productdescription { get; set; }
        [DataMember]
        public string productbrand { get; set; }
        [DataMember]
        public string productimage1 { get; set; }
        [DataMember]
        public Nullable<int> retailerid { get; set; }
        [DataMember]
        public Nullable<int> categoryid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCart> tblCarts { get; set; }
        public virtual tblCategory tblCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrder> tblOrders { get; set; }
        public virtual tblRetailer tblRetailer { get; set; }
    }
}
