//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingVS.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class tblUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUser()
        {
            this.tblCarts = new HashSet<tblCart>();
            this.tblOrders = new HashSet<tblOrder>();
        }
        [DataMember]
        public string useremail { get; set; }
        [DataMember]
        public string username { get; set; }
        [DataMember]
        public string userphone { get; set; }
        [DataMember]
        public string userpassword { get; set; }
        [DataMember]
        public string userapartment { get; set; }
        [DataMember]
        public string userstreet { get; set; }
        [DataMember]
        public string usertown { get; set; }
        [DataMember]
        public string userstate { get; set; }
        [DataMember]
        public string userpincode { get; set; }
        [DataMember]
        public string usercountry { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCart> tblCarts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrder> tblOrders { get; set; }
    }
}
